version: 2
updates:
  - package-ecosystem: "maven"
    directory: /apps/kafka-client-basic
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: /apps/kafka-streams-stateless
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: /apps/kafka-streams-stateful
    schedule:
      interval: "weekly"
